### ISSUE TITLE
Deepin Launcher do not open after upgrading to Deepin 20.2.3

### ISSUE THREAD

**Issue by eduardomozart** [linuxdeepin/dde-launcher#104]
After upgrading from Deepin 20.2.2 to Deepin 20.2.3 through ``sudo apt-get dist-upgrade`` command, the Deepin Launcher stopped working. When I attempt to open it, it just flashes a kind of blur kind of effect but do not open (screen capture below):

https://user-images.githubusercontent.com/2974895/131375148-52f321ee-0ac2-4721-95c7-2338a233f982.mp4

When I reboot the computer, it starts working again but after sometime it stops working again.

It works normally when I run ``dde-launcher`` from Terminal. Only the following errors are shown into Terminal when running ``dde-launcher``, but I do not believe they are related to this problem:

```
No appenders assotiated with category dde.dsvg
[Warning] <> set cache file modified date time failed, error message: "Argumento inválido" , cache file: "/home/eduardo/.cache/deepin/icons/62a0a25a24f8543edc46a21aea0673b2c153ba7a.png" , svg file: "/var/lib/flatpak/exports/share/icons/hicolor/scalable/apps/com.gitlab.ColinDuquesnoy.MellowPlayer.svg"
2021-08-30, 13:45:23.403 [Warning] [  ] libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by hhaim** [comment]
@ClayStan this issue wasn't solved in 20.3. In my case in some rare cases it works.
Any workaround for it?

**Comment by justforlxz** [comment]
> @ClayStan this issue wasn't solved in 20.3. In my case in some rare cases it works. Any workaround for it?

Execute this command to install some packages, `sudo apt install systemd-coredump dde-launcher-dbgsym`

Then

Run dde-launcher and wait for it to crash.
Then execute `sudo coredumpctl info /usr/bin/dde-launcher> /tmp/crash.log`
Please upload the /tmp/crash.log file. I think I should be able to analyze what went wrong.

**Comment by hhaim** [comment]
I just run it under gdb, the corefile is too big (32GB)

```
$gdb --args dde-launcher --show 

New Thread 0x7fff45ffb700 (LWP 6358)]
2021-11-25, 17:58:56.824 [Warning] [  ] qUncompress: Z_DATA_ERROR: Input data is corrupted
2021-11-25, 17:58:56.824 [Warning] [dsvgrenderer.cpp     Dtk::Gui::DSvgRenderer::load        293] DSvgRenderer::load: rsvg_handle_fill_with_data: assertion `data_len != 0' failed

Thread 9 "IconFreshThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe1981700 (LWP 6320)]
0x00007fffe2475f85 in QSvgIconEngine::read(QDataStream&) () from /usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/based-dtk/libdsvgicon.so
(gdb) bt
#0  0x00007fffe2475f85 in QSvgIconEngine::read(QDataStream&) () at /usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/based-dtk/libdsvgicon.so
#1  0x00007ffff694a920 in operator>>(QDataStream&, QIcon&) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#2  0x00007ffff04e78b7 in  () at /lib/x86_64-linux-gnu/libQt5XdgIconLoader.so.3
#3  0x00007fffe1171646 in XdgIconProxyEngine::followColorPixmap(ScalableEntry*, QSize const&, QIcon::Mode, QIcon::State) ()
    at /usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/based-dtk/libxdgicon.so
#4  0x00007fffe1172acf in XdgIconProxyEngine::pixmapByEntry(QIconLoaderEngineEntry*, QSize const&, QIcon::Mode, QIcon::State) ()
    at /usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/based-dtk/libxdgicon.so
#5  0x00007fffe1172eb8 in XdgIconProxyEngine::virtual_hook(int, void*) () at /usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/based-dtk/libxdgicon.so
#6  0x00007ffff6948bfb in QIcon::pixmap(QWindow*, QSize const&, QIcon::Mode, QIcon::State) const () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#7  0x00007ffff6948e9e in QIcon::pixmap(QSize const&, QIcon::Mode, QIcon::State) const () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#8  0x00000000004676e3 in  ()
#9  0x0000000000487720 in  ()
#10 0x00000000004879ab in  ()
#11 0x00007ffff62c49a8 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff59aafa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#13 0x00007ffff5e0e60f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) gcore dde-launce.core
warning: target file /proc/6309/cmdline contained unexpected null characters
warning: Memory read failed for corefile section, 4096 bytes at 0xffffffffff600000.
Saved corefile dde-launce.core

```

**Comment by hhaim** [comment]
@justforlxz does it help?

**Comment by hhaim** [comment]
@justforlxz @ClayStan attach
[crash.log](https://github.com/linuxdeepin/dde-launcher/files/7624499/crash.log)

**Comment by ClayStan** [comment]
Some wrong svg format will cause this problem, we are working on it

**Comment by hhaim** [comment]
@ClayStan is there a workaround? it is a app that I've installed? can I remove icon by icon to identify which svg create the issue?

**Comment by chenzhiwei** [comment]
I also encountered this issue.

Here is the log in my case: ~/.cache/deepin/dde-launcher/dde-launcher.log

```
2021-12-25, 13:21:03.499 [Warning] [  ] QWidget::setMinimumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (144,-1) are not possible
2021-12-25, 13:21:03.499 [Warning] [  ] QWidget::setMaximumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (144,-1) are not possible
2021-12-25, 13:21:03.499 [Warning] [  ] QWidget::setMinimumSize: (/AppGridView) Negative sizes (-44,-1) are not possible
2021-12-25, 13:21:03.508 [Warning] [  ] QWidget::setMinimumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (144,-1) are not possible
2021-12-25, 13:21:03.508 [Warning] [  ] QWidget::setMaximumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (144,-1) are not possible
2021-12-25, 13:21:03.508 [Warning] [  ] QWidget::setMinimumSize: (/AppGridView) Negative sizes (-44,-1) are not possible
2021-12-25, 13:21:03.508 [Warning] [  ] QWidget::setMinimumSize: (/AppGridView) Negative sizes (-44,-1) are not possible
2021-12-25, 13:21:03.640 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:03.640 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:03.641 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:03.641 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:03.641 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:03.641 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:03.641 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:03.641 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:03.641 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:03.641 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:03.641 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:03.641 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:03.641 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:03.641 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:04.431 [Warning] [  ] qUncompress: Z_DATA_ERROR: Input data is corrupted
2021-12-25, 13:21:04.432 [Warning] [dsvgrenderer.cpp     Dtk::Gui::DSvgRenderer::load        293] DSvgRenderer::load: rsvg_handle_fill_with_data: assertion `data_len != 0' failed
2021-12-25, 13:21:09.301 [Warning] [  ] QWidget::setMinimumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (144,-1) are not possible
2021-12-25, 13:21:09.301 [Warning] [  ] QWidget::setMaximumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (144,-1) are not possible
2021-12-25, 13:21:09.301 [Warning] [  ] QWidget::setMinimumSize: (/AppGridView) Negative sizes (-44,-1) are not possible
2021-12-25, 13:21:09.310 [Warning] [  ] QWidget::setMinimumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (144,-1) are not possible
2021-12-25, 13:21:09.310 [Warning] [  ] QWidget::setMaximumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (144,-1) are not possible
2021-12-25, 13:21:09.310 [Warning] [  ] QWidget::setMinimumSize: (/AppGridView) Negative sizes (-44,-1) are not possible
2021-12-25, 13:21:09.310 [Warning] [  ] QWidget::setMinimumSize: (/AppGridView) Negative sizes (-44,-1) are not possible
2021-12-25, 13:21:09.446 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:09.446 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:09.446 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:09.446 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:09.446 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:09.446 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:09.446 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:09.447 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:09.447 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:09.447 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:09.447 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:09.447 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:09.447 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2021-12-25, 13:21:09.447 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
```

**Comment by JiashunLi** [comment]
我的也是一样，从20.3开始在反馈这个问题，现在20.4 也没解决
就是刚开机的时候，点击开始按钮没有反应，多点几次就可以打开启动器了。不知道是开机启动项有延迟 还是咋的。
如果深度内部用的是这个系统 不可能不知道这个问题呀。
