### ISSUE TITLE
launcher in mini-mode crashes when clicking categories

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-launcher#17]
running **dde-launcher** in mini-mode and in category view, it segfaults when clicking on several categories:
```
(gdb) run /usr/bin/dde-launcher 
Starting program: /usr/bin/dde-launcher /usr/bin/dde-launcher
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe4928700 (LWP 10046)]

(dde-launcher:10045): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",

(dde-launcher:10045): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
[New Thread 0x7fffde050700 (LWP 10047)]
[New Thread 0x7fffdd642700 (LWP 10048)]
[New Thread 0x7fffdce41700 (LWP 10049)]
[New Thread 0x7fffcffff700 (LWP 10050)]
[New Thread 0x7fffc1c5b700 (LWP 10053)]
[New Thread 0x7fffc145a700 (LWP 10054)]

Thread 1 "dde-launcher" received signal SIGSEGV, Segmentation fault.
0x000000000045faf3 in ?? ()
(gdb) bt
#0  0x000000000045faf3 in  ()
#1  0x00007ffff42e4e72 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff54b0473 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#3  0x00007ffff558f2de in QFrame::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#4  0x00007ffff546f46c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff5476cf4 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff78a9bda in Dtk::Widget::DApplication::notify(QObject*, QEvent*) () at /usr/lib/libdtkwidget.so.1
#7  0x00007ffff42b5b98 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff42b802d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#9  0x00007ffff430da63 in  () at /usr/lib/libQt5Core.so.5
#10 0x00007ffff612aa47 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#11 0x00007ffff612ac78 in  () at /usr/lib/libglib-2.0.so.0
#12 0x00007ffff612ad0c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#13 0x00007ffff430de7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#14 0x00007ffff42b421a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#15 0x00007ffff42bca74 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#16 0x00000000004214e1 in main ()
```

**Comment by oberon2007** [comment]
Seems fixed with **deepin-launcher 4.1.1**, thank you! :smile:
